name: Release mosdns

on:
  push:
    tags:
      - 'v*'

jobs:

  build-release:
    runs-on: ubuntu-latest
    permissions: write-all # required by push tag
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Test
        run: go test -race -v ./...

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Build
        run: python ./release.py
        env:
          CGO_ENABLED: '0'

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: './release/mosdns*.zip'
